## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Sun Jun 29 19:07:07 EEST 2025
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
android.useAndroidX=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M" -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8 --add-opens java.base/java.util\=ALL-UNNAMED --add-opens java.base/java.lang\=ALL-UNNAMED --add-opens java.base/java.lang.invoke\=ALL-UNNAMED --add-opens java.base/java.util\=ALL-UNNAMED --add-opens java.prefs/java.util.prefs\=ALL-UNNAMED --add-opens java.base/java.nio.charset\=ALL-UNNAMED --add-opens java.base/java.net\=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic\=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.unsafe.configuration-cache=false
org.gradle.jvmargs=-Xmx4g
