apply plugin: 'com.android.library'

android {
    compileSdk 33

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])

    //Required dependencies---start
    //homesdk basic capabilities
    api "com.thingclips.smart:thingsmart:${sdk_version}"

    api enforcedPlatform("com.thingclips.smart:thingsmart-BizBundlesBom:${biz_bom_version}")

    //Device control business package RN container
    api "com.thingclips.smart:thingsmart-bizbundle-panel:${biz_bom_version}"
    //Basic extension capabilities
    api("com.thingclips.smart:thingsmart-bizbundle-basekit") {
        exclude group: "com.thingclips.smart", module: "thingplugin-annotation"
    }
    //Tuya business extension capabilities
    // api("com.thingclips.smart:thingsmart-bizbundle-commonbiz") {
    //     exclude group: "com.thingclips.smart", module: "thingplugin-annotation"
    // }
    //Device control related capabilities
    api("com.thingclips.smart:thingsmart-bizbundle-control") {
        exclude group: "com.thingclips.smart", module: "thingplugin-annotation"
    }

    //Strongly recommended to include---start
    //Family related dependencies
    api("com.thingclips.smart:thingsmart-bizbundle-family") {
        exclude group: "com.thingclips.smart", module: "thingplugin-annotation"
    }
    //Location extension capabilities
    // api("com.thingclips.smart:thingsmart-bizbundle-location") {
    //     exclude group: "com.thingclips.smart", module: "thingplugin-annotation"
    // }
    //Multimedia extension capabilities
    // api("com.thingclips.smart:thingsmart-bizbundle-multimedia") {
    //     exclude group: "com.thingclips.smart", module: "thingplugin-annotation"
    // }
    api "com.thingclips.smart:thingsmart-bizbundle-mediakit"

    api "com.thingclips.smart:thingsmart-ipcsdk:${ipc_sdk_version}"
    //Optional dependencies---start
    //IPC panel related dependencies
    api "com.thingclips.smart:thingsmart-bizbundle-camera_panel"

    // AMap (Gaode Map)
    implementation 'com.amap.api:search:7.9.0'
    implementation 'com.amap.api:3dmap:8.1.0'
    api 'com.thingclips.smart:thingsmart-react-native-amap:4.5.0-rc.1'
    // Google Maps
    api 'com.thingclips.smart:thingsmart-react-native-googlemap:4.5.0-rc.1'
    api 'com.google.android.gms:play-services-maps:18.0.0'

    // qq music (speaker products)
    api("com.tencent.yunxiaowei.dmsdk:core:2.3.0") {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
    api("com.tencent.yunxiaowei.webviewsdk:webviewsdk:2.3.0") {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
}

